### PR TITLE
Change .TXT references in project to .MD

### PR DESCRIPTION
**Pull request by mikepotjer**
- Update the project references to the .TXT files that have been
  renamed to .MD.
- Set the Anchor for the Filter button so it remains on the right
  hand side of the form.
- Add a .gitignore file to make sure certain files are excluded from
  the repository.

### CODE REVIEW

**Comment by eselje** [comment]
Mike, thanks for contributing! Can you send me a screenshot of what the Help, About files look like? That screen displayed the information in txt files. Will it still work if they're MD files? (Would be nice if they did).

**Comment by mikepotjer** [comment]
The short answer is that MD files work fine in the About screen. The .MD extension is just the standard extension to indicate that the file is a text file using Markdown formatting. If you're not familiar with it, Markdown is just plain text with a few special characters used to indicate formatting. It's intended to be human-readable as-is, but a Markdown parser like that used by GitHub can make it look nice. Login to GitHub and view the MD files there to see what I mean. Steven Black only applied minor formatting to the files that were compiled into the app, so they are nearly identical to what they were before. Below are screenshots of all 4 files as they now appear in the About screen. The highlighted lines are the lines using Markdown formatting.

image
image
image
image

**Comment by eselje** [comment]
Ok, that looks good to me. It'd be sweet if the markdown got translated into the actual formatting, but it definitely looks good enough here. Thanks for doing this!

**Comment by mikepotjer** [comment]
You're welcome! Happy to be able to contribute.

**Pull request merged**
